"""v2 quality: reviews, content_versions, registration_challenges, review_status

Revision ID: b0e29aefaa17
Revises: 410e62dbaab8
Create Date: 2026-03-19 19:28:02.118007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e29aefaa17'
down_revision: Union[str, None] = '410e62dbaab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lean_statement', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'target_type', 'version', name='uq_content_versions_target_version')
    )
    op.create_table('registration_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('challenge_statement', sa.Text(), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), server_default='5', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reg_challenges_name', 'registration_challenges', ['name', 'completed'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('conjecture', 'problem')", name='reviews_target_type_check'),
    sa.CheckConstraint("verdict IN ('approve', 'request_changes')", name='reviews_verdict_check'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'target_type', 'reviewer_id', 'version', name='uq_reviews_target_reviewer_version')
    )
    op.create_index('idx_reviews_target', 'reviews', ['target_id', 'target_type', 'version'], unique=False)
    op.add_column('conjectures', sa.Column('review_status', sa.String(length=20), server_default='approved', nullable=False))
    op.add_column('conjectures', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('problems', sa.Column('review_status', sa.String(length=20), server_default='approved', nullable=False))
    op.add_column('problems', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'version')
    op.drop_column('problems', 'review_status')
    op.drop_column('conjectures', 'version')
    op.drop_column('conjectures', 'review_status')
    op.drop_index('idx_reviews_target', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_reg_challenges_name', table_name='registration_challenges')
    op.drop_table('registration_challenges')
    op.drop_table('content_versions')
    # ### end Alembic commands ###
